# Generated by Django 4.2.7 on 2024-11-23 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_gen', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BarcodeRegistrationModel',
            new_name='CodeRegistrationModel',
        ),
        migrations.AlterModelOptions(
            name='coderegistrationmodel',
            options={'verbose_name': 'Code Registration', 'verbose_name_plural': 'Code Registrations'},
        ),
        migrations.AlterModelTable(
            name='coderegistrationmodel',
            table='apps_project_specific_internal_code_gen_code_registration',
        ),
    ]
