# Generated by Django 4.2.13 on 2024-12-03 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('asset_es', models.CharField(max_length=255, verbose_name='Asset (ES)')),
                ('asset_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asset (EN)')),
                ('quantity_type', models.CharField(choices=[('O', 'Other'), ('U', 'Units'), ('B', 'Boxes'), ('C', 'Containers')], default='B', max_length=255, verbose_name='quantity type')),
                ('offer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Offer Amount per quantity type in (USD BIS)')),
                ('offer_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity needed')),
                ('buyer_country', models.CharField(max_length=100, verbose_name='Buyer Country')),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_offer_assetcategory', to='assets.assetcategorymodel', verbose_name='category')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_offers_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': '1. Offer',
                'verbose_name_plural': '1. Offers',
                'db_table': 'apps_buyers_offer',
                'ordering': ['default_order', '-created'],
            },
        ),
    ]
