# Generated by Django 4.2.7 on 2024-12-05 03:00

import apps.project.specific.assets_management.buyers.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_location', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('asset_es', models.CharField(max_length=255, verbose_name='Asset (ES)')),
                ('asset_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Asset (EN)')),
                ('offer_type', models.CharField(choices=[('S', 'Sovereign Purchase'), ('P', 'Private Purchase (Sovereign)'), ('B', 'Business Purchase'), ('G', 'Government Purchase')], default='P', max_length=255, verbose_name='Offer Type')),
                ('quantity_type', models.CharField(choices=[('O', 'Other'), ('U', 'Units'), ('B', 'Boxes'), ('C', 'Containers')], default='B', max_length=255, verbose_name='quantity type')),
                ('offer_amount', models.DecimalField(decimal_places=1, default=0, max_digits=20, verbose_name='Offer Amount per quantity type in USD')),
                ('offer_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity needed')),
                ('procedure', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Procedure')),
                ('banner', models.ImageField(blank=True, null=True, upload_to=apps.project.specific.assets_management.buyers.models.OfferModel.offers_directory_path, verbose_name='Banner')),
                ('asset_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_offer_assetcategory', to='assets.assetcategorymodel', verbose_name='category')),
                ('buyer_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_offer_country', to='assets_location.assetcountrymodel', verbose_name='Country')),
            ],
            options={
                'verbose_name': '1. Offer',
                'verbose_name_plural': '1. Offers',
                'db_table': 'apps_buyers_offer',
                'ordering': ['default_order', '-created'],
            },
        ),
    ]
