# Generated by Django 4.2.7 on 2024-12-17 05:57

import apps.project.specific.assets_management.buyers.models
from django.db import migrations, models
import django.utils.timezone
import django_ckeditor_5.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferModel',
            fields=[
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID')),
                ('offer_type', models.CharField(choices=[('S', 'Sovereign Purchase'), ('P', 'Private Purchase (Sovereign)'), ('B', 'Business Purchase'), ('G', 'Government Purchase')], default='P', max_length=255, verbose_name='Offer Type')),
                ('quantity_type', models.CharField(choices=[('U', 'Units'), ('B', 'Boxes'), ('C', 'Containers')], default='B', max_length=255, verbose_name='quantity type')),
                ('offer_amount', models.DecimalField(decimal_places=1, default=0, max_digits=20, verbose_name='Offer Amount per quantity type in USD')),
                ('offer_quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity needed')),
                ('es_procedure', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Procedure (ES)')),
                ('en_procedure', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Procedure (EN)')),
                ('es_banner', models.ImageField(blank=True, null=True, upload_to=apps.project.specific.assets_management.buyers.models.OfferModel.offers_directory_path, verbose_name='Banner (ES)')),
                ('en_banner', models.ImageField(blank=True, null=True, upload_to=apps.project.specific.assets_management.buyers.models.OfferModel.offers_directory_path, verbose_name='Banner (EN)')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Approved')),
            ],
            options={
                'verbose_name': '1. Offer',
                'verbose_name_plural': '1. Offers',
                'db_table': 'apps_buyers_offer',
                'ordering': ['default_order', '-created'],
            },
        ),
    ]
