# Generated by Django 4.2.7 on 2024-12-15 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets_location', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0001_initial'),
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_approved_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyers_offer_asset', to='assets.assetmodel', verbose_name='Asset'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='buyer_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_offer_country', to='assets_location.assetcountrymodel', verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
    ]
