# Generated by Django 4.2.13 on 2024-12-03 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assets_location', '0002_initial'),
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='buyer_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buyers_offer_country', to='assets_location.assetcountrymodel', verbose_name='Country'),
        ),
    ]
