# Generated by Django 4.2.7 on 2024-12-21 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='en_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description (EN)'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='en_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation (EN)'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='es_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description (ES)'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='es_observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation (ES)'),
        ),
    ]
