# Generated by Django 4.2.13 on 2024-12-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0002_alter_offermodel_buyer_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='offer_amount',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=20, verbose_name='Offer Amount per quantity type in (BIS)'),
        ),
    ]
