# Generated by Django 4.2.7 on 2024-12-06 07:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('buyers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyers_offer_approved_by_user', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
    ]
