# Generated by Django 4.2.13 on 2024-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_alter_offermodel_offer_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='offermodel',
            name='offer_type',
            field=models.CharField(choices=[('S', 'Sovereign Purchase'), ('P', 'Private Purchase (Sovereign)'), ('B', 'Business Purchase'), ('G', 'Government Purchase')], default='P', max_length=255, verbose_name='Offer Type'),
        ),
    ]
