# Generated by Django 4.2.7 on 2024-12-06 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0003_alter_offermodel_approved_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offermodel',
            old_name='approved',
            new_name='is_approved',
        ),
    ]
