# Generated by Django 4.2.7 on 2024-12-06 07:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0004_rename_approved_offermodel_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offermodel',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='ID'),
        ),
    ]
