# Generated by Django 4.2.7 on 2024-12-10 03:34

import apps.project.specific.assets_management.buyers.models
from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0005_alter_offermodel_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offermodel',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='offermodel',
            name='procedure',
        ),
        migrations.AddField(
            model_name='offermodel',
            name='en_banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.project.specific.assets_management.buyers.models.OfferModel.offers_directory_path, verbose_name='Banner (EN)'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='en_procedure',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Procedure (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offermodel',
            name='es_banner',
            field=models.ImageField(blank=True, null=True, upload_to=apps.project.specific.assets_management.buyers.models.OfferModel.offers_directory_path, verbose_name='Banner (ES)'),
        ),
        migrations.AddField(
            model_name='offermodel',
            name='es_procedure',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Procedure (ES)'),
            preserve_default=False,
        ),
    ]
