# Generated by Django 4.2.13 on 2024-12-03 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='is_buyer',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='is_holder',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('O', 'Other'), ('B', 'Buyer'), ('H', 'Holder')], default='H', max_length=2, verbose_name='User'),
        ),
    ]
