# Generated by Django 4.2.7 on 2024-11-29 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='is_buyer',
            field=models.BooleanField(default=False, verbose_name='Buyer'),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='is_holder',
            field=models.BooleanField(default=False, verbose_name='Holder'),
        ),
    ]
