# Generated by Django 4.2.13 on 2024-12-03 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_usermodel_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_type',
            field=models.CharField(choices=[('H', 'Holder'), ('R', 'Representative'), ('B', 'Buyer'), ('I', 'Intermediary')], default='H', max_length=2, verbose_name='User'),
        ),
    ]
