# Generated by Django 4.2.7 on 2025-01-10 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModalBannerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='title (English)')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('image_file', models.ImageField(upload_to='modal_banners/', verbose_name='image file')),
                ('image_file_en', models.ImageField(blank=True, null=True, upload_to='modal_banners/', verbose_name='image file (English)')),
                ('link', models.URLField(blank=True, max_length=255, null=True, verbose_name='link')),
                ('link_en', models.URLField(blank=True, max_length=255, null=True, verbose_name='link (English)')),
            ],
            options={
                'verbose_name': 'Modal Banner',
                'verbose_name_plural': 'Modal Banners',
                'db_table': 'apps_common_core_modal_banner',
                'ordering': ['-created'],
            },
        ),
    ]
