# Generated by Django 4.2.7 on 2024-11-28 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_contactmodel_unique_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactmodel',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
    ]
