# Generated by Django 4.2.7 on 2024-11-29 03:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_assets_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='assetcategorymodel',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_assetcategory_user', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterUniqueTogether(
            name='assetmodel',
            unique_together={('name', 'quantity_type')},
        ),
    ]
