# Generated by Django 4.2.7 on 2024-11-29 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmodel',
            name='quantity_type',
            field=models.CharField(choices=[('O', 'Other'), ('U', 'Units'), ('B', 'Boxes'), ('C', 'Containers')], default='B', max_length=255, verbose_name='quantity type'),
        ),
    ]
