# Generated by Django 4.2.13 on 2024-12-03 07:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetmodel',
            unique_together={('name', 'es_name', 'quantity_type', 'created_by')},
        ),
    ]
