# Generated by Django 4.2.7 on 2024-11-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcategorymodel',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='assetcategorymodel',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='category (EN)'),
        ),
        migrations.AlterField(
            model_name='assetmodel',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='english name'),
        ),
    ]
