# Generated by Django 4.2.7 on 2024-11-11 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatemodel',
            name='document_number_hash',
            field=models.CharField(default='', editable=False, max_length=64),
        ),
    ]
