# Generated by Django 4.2.7 on 2024-11-11 20:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('certificates', '0002_certificatemodel_document_number_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatemodel',
            name='last_name',
            field=models.CharField(default='', max_length=100, verbose_name='Last name'),
        ),
        migrations.AddField(
            model_name='certificatemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='certificatemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Names'),
        ),
        migrations.AlterModelTable(
            name='certificatemodel',
            table='apps_project_specific_documents_certificates_certificate',
        ),
    ]
