# Generated by Django 4.2.7 on 2024-11-15 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0003_certificatemodel_last_name_certificatemodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificatemodel',
            name='step',
        ),
    ]
