# Generated by Django 4.2.7 on 2024-11-29 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLoginAttemptModel',
        ),
    ]
