# Generated by Django 4.2.7 on 2024-12-05 03:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('country_name', models.CharField(max_length=100, unique=True, verbose_name='Country Name')),
            ],
            options={
                'verbose_name': '3. Country',
                'verbose_name_plural': '3. Countries',
                'db_table': 'apps_assets_location_country',
            },
        ),
        migrations.CreateModel(
            name='AssetLocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('amount', models.PositiveBigIntegerField(verbose_name='amount')),
            ],
            options={
                'verbose_name': '1. Location Registration',
                'verbose_name_plural': '1. Locations Registration',
                'db_table': 'apps_assets_location_assetlocation',
                'ordering': ['default_order', 'asset', '-created'],
            },
        ),
        migrations.CreateModel(
            name='LocationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(blank=True, choices=[('es', 'Spanish'), ('en', 'English')], default='es', max_length=4, null=True, verbose_name='language')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('default_order', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='priority')),
                ('reference', models.CharField(max_length=150, verbose_name='reference')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('continent', models.CharField(choices=[('AF', 'Africa'), ('AN', 'Antarctica'), ('AS', 'Asia'), ('CA', 'Central America'), ('EU', 'Europe'), ('NA', 'North America'), ('OC', 'Oceania'), ('SA', 'South America')], default='EU', max_length=3, verbose_name='continent')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assetlocation_location_country', to='assets_location.assetcountrymodel', verbose_name='Country')),
            ],
            options={
                'verbose_name': '2. Location',
                'verbose_name_plural': '2. Locations',
                'db_table': 'apps_assets_location_location',
                'ordering': ['default_order', 'reference', '-created'],
            },
        ),
    ]
