# Generated by Django 4.2.7 on 2024-11-29 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_location', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetcountrymodel',
            name='country_code',
        ),
    ]
