# Generated by Django 4.2.7 on 2024-11-29 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets_location', '0003_remove_assetcountrymodel_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationmodel',
            options={'ordering': ['default_order', 'reference', '-created'], 'verbose_name': '2. Location', 'verbose_name_plural': '2. Locations'},
        ),
        migrations.RemoveField(
            model_name='locationmodel',
            name='owner',
        ),
    ]
