# Generated by Django 4.2.7 on 2024-12-10 22:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets_location', '0003_alter_locationmodel_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationmodel',
            unique_together={('reference', 'country', 'created_by')},
        ),
    ]
