# Generated by Django 4.2.7 on 2024-12-12 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets_location', '0004_alter_locationmodel_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmodel',
            name='reference',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='location reference'),
        ),
    ]
